// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz41DQq1aZOG-5sFLywlv7L3YiZWLVhL8',
    appId: '1:292383295028:web:547cd6b5de69163f3cec61',
    messagingSenderId: '292383295028',
    projectId: 'silsilahapps',
    authDomain: 'silsilahapps.firebaseapp.com',
    storageBucket: 'silsilahapps.firebasestorage.app',
    measurementId: 'G-FQ6KPDEBHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDGEbBg-HlZU9tyiJkCppexI7R8E4z02U',
    appId: '1:292383295028:android:fafc07a9cd330fb33cec61',
    messagingSenderId: '292383295028',
    projectId: 'silsilahapps',
    storageBucket: 'silsilahapps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf2iVD2531LlR3CxzVVccjHLVu7KtC26w',
    appId: '1:292383295028:ios:5414fdda2df977553cec61',
    messagingSenderId: '292383295028',
    projectId: 'silsilahapps',
    storageBucket: 'silsilahapps.firebasestorage.app',
    iosBundleId: 'com.example.silsilahApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf2iVD2531LlR3CxzVVccjHLVu7KtC26w',
    appId: '1:292383295028:ios:5414fdda2df977553cec61',
    messagingSenderId: '292383295028',
    projectId: 'silsilahapps',
    storageBucket: 'silsilahapps.firebasestorage.app',
    iosBundleId: 'com.example.silsilahApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz41DQq1aZOG-5sFLywlv7L3YiZWLVhL8',
    appId: '1:292383295028:web:afbd88d63f32d8253cec61',
    messagingSenderId: '292383295028',
    projectId: 'silsilahapps',
    authDomain: 'silsilahapps.firebaseapp.com',
    storageBucket: 'silsilahapps.firebasestorage.app',
    measurementId: 'G-4T81V9SE4Z',
  );
}
